version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mygraphql
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - graphql_network

networks:
  graphql_network:
    driver: bridge
